
# QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:20.10.0
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
x-quorum-def:
  &quorum-def
  # restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:20.10.0}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 4s
    timeout: 4s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: raft
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /nodes/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /nodes/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /nodes/permissioned-nodes.json > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/nodes/genesis.json"
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --allow-insecure-unlock \
        --identity node$${NODE_ID}-raft \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpccorsdomain "*" \
        --rpcvhosts "*" \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --port 21000 \
        --ws \
        --wsaddr 0.0.0.0 \
        --wsport 8546 \
        --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --wsorigins "*" \
        --unlock 0 \
        --password /nodes/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_raft}
services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22001:8545"
      - "23001:8546"
    volumes:
      - vol1:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=1
    networks:
      quorum-net:
        ipv4_address: 172.16.239.11
  node2:
    << : *quorum-def
    hostname: node2
    ports:
      - "22002:8545"
      - "23002:8546"
    volumes:
      - vol2:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=2
    networks:
      quorum-net:
        ipv4_address: 172.16.239.12
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22003:8545"
      - "23003:8546"
    volumes:
      - vol3:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=3
    networks:
      quorum-net:
        ipv4_address: 172.16.239.13
  node4:
    << : *quorum-def
    hostname: node4
    ports:
      - "22004:8545"
      - "23004:8546"
    volumes:
      - vol4:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=4
    networks:
      quorum-net:
        ipv4_address: 172.16.239.14
  node5:
    << : *quorum-def
    hostname: node5
    ports:
      - "22005:8545"
      - "23005:8546"
    volumes:
      - vol5:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=5
    networks:
      quorum-net:
        ipv4_address: 172.16.239.15
  node6:
    << : *quorum-def
    hostname: node6
    ports:
      - "22006:8545"
      - "23006:8546"
    volumes:
      - vol6:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=6
    networks:
      quorum-net:
        ipv4_address: 172.16.239.16

  node7:
    << : *quorum-def
    hostname: node7
    ports:
      - "22007:8545"
      - "23007:8546"
    volumes:
      - vol7:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=7
    networks:
      quorum-net:
        ipv4_address: 172.16.239.17

  node8:
    << : *quorum-def
    hostname: node8
    ports:
      - "22008:8545"
      - "23008:8546"
    volumes:
      - vol8:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=8
    networks:
      quorum-net:
        ipv4_address: 172.16.239.18

  node9:
    << : *quorum-def
    hostname: node9
    ports:
      - "22009:8545"
      - "23009:8546"
    volumes:
      - vol9:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=9
    networks:
      quorum-net:
        ipv4_address: 172.16.239.19 

  node10:
    << : *quorum-def
    hostname: node10
    ports:
      - "22010:8545"
      - "23010:8546"
    volumes:
      - vol10:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=10
    networks:
      quorum-net:
        ipv4_address: 172.16.239.110  

  node11:
    << : *quorum-def
    hostname: node11
    ports:
      - "22011:8545"
      - "23011:8546"
    volumes:
      - vol11:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=11
    networks:
      quorum-net:
        ipv4_address: 172.16.239.111

  node12:
    << : *quorum-def
    hostname: node12
    ports:
      - "22012:8545"
      - "23012:8546"
    volumes:
      - vol12:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=12
    networks:
      quorum-net:
        ipv4_address: 172.16.239.112 

  node13:
    << : *quorum-def
    hostname: node13
    ports:
      - "22013:8545"
      - "23013:8546"
    volumes:
      - vol13:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=13
    networks:
      quorum-net:
        ipv4_address: 172.16.239.113  

  node14:
    << : *quorum-def
    hostname: node14
    ports:
      - "22014:8545"
      - "23014:8546"
    volumes:
      - vol14:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=14
    networks:
      quorum-net:
        ipv4_address: 172.16.239.114  

  node15:
    << : *quorum-def
    hostname: node15
    ports:
      - "22015:8545"
      - "23015:8546"
    volumes:
      - vol15:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=15
    networks:
      quorum-net:
        ipv4_address: 172.16.239.115  

  node16:
    << : *quorum-def
    hostname: node16
    ports:
      - "22016:8545"
      - "23016:8546"
    volumes:
      - vol16:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=16
    networks:
      quorum-net:
        ipv4_address: 172.16.239.116

  node17:
    << : *quorum-def
    hostname: node17
    ports:
      - "22017:8545"
      - "23017:8546"
    volumes:
      - vol17:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=17
    networks:
      quorum-net:
        ipv4_address: 172.16.239.117

  node18:
    << : *quorum-def
    hostname: node18
    ports:
      - "22018:8545"
      - "23018:8546"
    volumes:
      - vol18:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=18
    networks:
      quorum-net:
        ipv4_address: 172.16.239.118

  node19:
    << : *quorum-def
    hostname: node19
    ports:
      - "22019:8545"
      - "23019:8546"
    volumes:
      - vol19:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=19
    networks:
      quorum-net:
        ipv4_address: 172.16.239.119

  node20:
    << : *quorum-def
    hostname: node20
    ports:
      - "22020:8545"
      - "23020:8546"
    volumes:
      - vol20:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=20
    networks:
      quorum-net:
        ipv4_address: 172.16.239.120

  node21:
    << : *quorum-def
    hostname: node21
    ports:
      - "22021:8545"
      - "23021:8546"
    volumes:
      - vol21:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=21
    networks:
      quorum-net:
        ipv4_address: 172.16.239.121

  node22:
    << : *quorum-def
    hostname: node22
    ports:
      - "22022:8545"
      - "23022:8546"
    volumes:
      - vol22:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=22
    networks:
      quorum-net:
        ipv4_address: 172.16.239.122

  node23:
    << : *quorum-def
    hostname: node23
    ports:
      - "22023:8545"
      - "23023:8546"
    volumes:
      - vol23:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=23
    networks:
      quorum-net:
        ipv4_address: 172.16.239.123

  node24:
    << : *quorum-def
    hostname: node24
    ports:
      - "22024:8545"
      - "23024:8546"
    volumes:
      - vol24:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=24
    networks:
      quorum-net:
        ipv4_address: 172.16.239.124

  node25:
    << : *quorum-def
    hostname: node25
    ports:
      - "22025:8545"
      - "23025:8546"
    volumes:
      - vol25:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=25
    networks:
      quorum-net:
        ipv4_address: 172.16.239.125

  node26:
    << : *quorum-def
    hostname: node26
    ports:
      - "22026:8545"
      - "23026:8546"
    volumes:
      - vol26:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=26
    networks:
      quorum-net:
        ipv4_address: 172.16.239.126
  
  node27:
    << : *quorum-def
    hostname: node27
    ports:
      - "22027:8545"
      - "23027:8546"
    volumes:
      - vol27:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=27
    networks:
      quorum-net:
        ipv4_address: 172.16.239.127

  node28:
    << : *quorum-def
    hostname: node28
    ports:
      - "22028:8545"
      - "23028:8546"
    volumes:
      - vol28:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=28
    networks:
      quorum-net:
        ipv4_address: 172.16.239.128 

  node29:
    << : *quorum-def
    hostname: node29
    ports:
      - "22029:8545"
      - "23029:8546"
    volumes:
      - vol29:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=29
    networks:
      quorum-net:
        ipv4_address: 172.16.239.129 

  node30:
    << : *quorum-def
    hostname: node30
    ports:
      - "22030:8545"
      - "23030:8546"
    volumes:
      - vol30:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=30
    networks:
      quorum-net:
        ipv4_address: 172.16.239.130

  node31:
    << : *quorum-def
    hostname: node31
    ports:
      - "22031:8545"
      - "23031:8546"
    volumes:
      - vol31:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=31
    networks:
      quorum-net:
        ipv4_address: 172.16.239.131 

  node32:
    << : *quorum-def
    hostname: node32
    ports:
      - "22032:8545"
      - "23032:8546"
    volumes:
      - vol32:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=32
    networks:
      quorum-net:
        ipv4_address: 172.16.239.132 

networks:
  quorum-net:
    name: quorum-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol4":
  "vol5":
  "vol6":
  "vol7":
  "vol8":
  "vol9":
  "vol10":
  "vol11":
  "vol12":
  "vol13":
  "vol14":
  "vol15":
  "vol16":
  "vol17":
  "vol18":
  "vol19":
  "vol20":
  "vol21":
  "vol22":
  "vol23":
  "vol24":
  "vol25":
  "vol26":
  "vol27":
  "vol28":
  "vol29":
  "vol30":
  "vol31":
  "vol32":
