
# QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:20.10.0
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
x-quorum-def:
  &quorum-def
  # restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:20.10.0}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 4s
    timeout: 4s
    retries: 20
    start_period: 5s
  labels:
    com.quorum.consensus: raft
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /nodes/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /nodes/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /nodes/permissioned-nodes.json > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/nodes/genesis.json"
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --allow-insecure-unlock \
        --identity node$${NODE_ID}-raft \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpccorsdomain "*" \
        --rpcvhosts "*" \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --port 21000 \
        --ws \
        --wsaddr 0.0.0.0 \
        --wsport 8546 \
        --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --wsorigins "*" \
        --unlock 0 \
        --password /nodes/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_raft}
services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22001:8545"
      - "23001:8546"
    volumes:
      - vol1:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=1
    networks:
      quorum-net:
        ipv4_address: 172.16.239.11
  node2:
    << : *quorum-def
    hostname: node2
    ports:
      - "22002:8545"
      - "23002:8546"
    volumes:
      - vol2:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=2
    networks:
      quorum-net:
        ipv4_address: 172.16.239.12
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22003:8545"
      - "23003:8546"
    volumes:
      - vol3:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=3
    networks:
      quorum-net:
        ipv4_address: 172.16.239.13
  node4:
    << : *quorum-def
    hostname: node4
    ports:
      - "22004:8545"
      - "23004:8546"
    volumes:
      - vol4:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=4
    networks:
      quorum-net:
        ipv4_address: 172.16.239.14
  node5:
    << : *quorum-def
    hostname: node5
    ports:
      - "22005:8545"
      - "23005:8546"
    volumes:
      - vol5:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=5
    networks:
      quorum-net:
        ipv4_address: 172.16.239.15
  node6:
    << : *quorum-def
    hostname: node6
    ports:
      - "22006:8545"
      - "23006:8546"
    volumes:
      - vol6:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=6
    networks:
      quorum-net:
        ipv4_address: 172.16.239.16

  node7:
    << : *quorum-def
    hostname: node7
    ports:
      - "22007:8545"
      - "23007:8546"
    volumes:
      - vol7:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=7
    networks:
      quorum-net:
        ipv4_address: 172.16.239.17

  node8:
    << : *quorum-def
    hostname: node8
    ports:
      - "22008:8545"
      - "23008:8546"
    volumes:
      - vol8:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=8
    networks:
      quorum-net:
        ipv4_address: 172.16.239.18

  node9:
    << : *quorum-def
    hostname: node9
    ports:
      - "22009:8545"
      - "23009:8546"
    volumes:
      - vol9:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=9
    networks:
      quorum-net:
        ipv4_address: 172.16.239.19 

  node10:
    << : *quorum-def
    hostname: node10
    ports:
      - "22010:8545"
      - "23010:8546"
    volumes:
      - vol10:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=10
    networks:
      quorum-net:
        ipv4_address: 172.16.239.110  

  node11:
    << : *quorum-def
    hostname: node11
    ports:
      - "22011:8545"
      - "23011:8546"
    volumes:
      - vol11:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=11
    networks:
      quorum-net:
        ipv4_address: 172.16.239.111

  node12:
    << : *quorum-def
    hostname: node12
    ports:
      - "22012:8545"
      - "23012:8546"
    volumes:
      - vol12:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=12
    networks:
      quorum-net:
        ipv4_address: 172.16.239.112 

  node13:
    << : *quorum-def
    hostname: node13
    ports:
      - "22013:8545"
      - "23013:8546"
    volumes:
      - vol13:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=13
    networks:
      quorum-net:
        ipv4_address: 172.16.239.113  

  node14:
    << : *quorum-def
    hostname: node14
    ports:
      - "22014:8545"
      - "23014:8546"
    volumes:
      - vol14:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=14
    networks:
      quorum-net:
        ipv4_address: 172.16.239.114  

  node15:
    << : *quorum-def
    hostname: node15
    ports:
      - "22015:8545"
      - "23015:8546"
    volumes:
      - vol15:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=15
    networks:
      quorum-net:
        ipv4_address: 172.16.239.115  

  node16:
    << : *quorum-def
    hostname: node16
    ports:
      - "22016:8545"
      - "23016:8546"
    volumes:
      - vol16:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=16
    networks:
      quorum-net:
        ipv4_address: 172.16.239.116

networks:
  quorum-net:
    name: quorum-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol4":
  "vol5":
  "vol6":
  "vol7":
  "vol8":
  "vol9":
  "vol10":
  "vol11":
  "vol12":
  "vol13":
  "vol14":
  "vol15":
  "vol16":
