
# QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:20.10.0
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
x-quorum-def:
  &quorum-def
  # restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:20.10.0}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 4s
    timeout: 4s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: raft
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /nodes/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /nodes/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /nodes/permissioned-nodes.json > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/nodes/genesis.json"
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --allow-insecure-unlock \
        --identity node$${NODE_ID}-raft \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpccorsdomain "*" \
        --rpcvhosts "*" \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --port 21000 \
        --ws \
        --wsaddr 0.0.0.0 \
        --wsport 8546 \
        --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --wsorigins "*" \
        --unlock 0 \
        --password /nodes/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_raft}
services:
  node1:
    << : *quorum-def
    container_name: node1
    hostname: node1
    ports:
      - "22001:8545"
      - "23001:8546"
    volumes:
      - vol1:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=1
    networks:
      quorum-net:
        ipv4_address: 172.16.239.11
  node2:
    << : *quorum-def
    container_name: node2
    hostname: node2
    ports:
      - "22002:8545"
      - "23002:8546"
    volumes:
      - vol2:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=2
    networks:
      quorum-net:
        ipv4_address: 172.16.239.12
  node3:
    << : *quorum-def
    container_name: node3
    hostname: node3
    ports:
      - "22003:8545"
      - "23003:8546"
    volumes:
      - vol3:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=3
    networks:
      quorum-net:
        ipv4_address: 172.16.239.13
  node4:
    << : *quorum-def
    container_name: node4
    hostname: node4
    ports:
      - "22004:8545"
      - "23004:8546"
    volumes:
      - vol4:/qdata
      - ./nodes:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=4
    networks:
      quorum-net:
        ipv4_address: 172.16.239.14

networks:
  quorum-net:
    name: quorum-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol4":